### ISSUE TITLE
Punctuation improvments

### ISSUE THREAD

**Issue by simurai** [atom/language-c#103]
Originally reported in https://github.com/simurai/duotone-dark-syntax/issues/8. Punctuations aren't supported that well.

For example if you try to highlight any general `.punctuation` with 

``` css
atom-text-editor::shadow .punctuation {
  color: red !important;
}
```

in this example:

``` c
int main()
{
  str = malloc(count * sizeof(int));
  die("Memory error.");
}
```

most parentheses and semicolons aren't styled (red) and just "plain text".

![screen shot 2015-11-24 at 9 07 44 am](https://cloud.githubusercontent.com/assets/378023/11353989/82739da8-928b-11e5-84ac-c169386f92f1.png)
